name: Playwright E2E Tests (Only on Manual Run)
run-name: "${{ inputs.deployment-environment }}: ${{ inputs.build-number }}"

on:
   workflow_dispatch:
     inputs:
      build-number:
        description: Build number to deploy
        required: true
        type: string
      deployment-environment:
        required: true
        description: Deployment environment
        type: choice
        options:
          - development
          - test
          - production

permissions:
  contents: read
  id-token: write

# Prevent multiple run to the same deployment environment from running at the same time.
concurrency: ${{ inputs.deployment-environment }}-e2e-tests

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Build Number
        run: |
          echo "Build #${{ github.run_number }}" > build-number-test.txt

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Angular in Background
        run: npm run start &
        env:
          CI: true

      - name: Run Playwright Tests
        run: npx playwright test
        
      - name: Upload Playwright Videos and Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: playwright-report/
          retention-days: 7
          
         # Install Allure CLI in GitHub Runner
      - name: Install Allure CLI
        run: npm i -g allure-commandline  
  
          
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean
        
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 5  # Keep the artifact for 5 days
    
  
