name: Update README with Build Number

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Replace placeholder with latest GitHub run number
      - name: Update README
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          echo "Updating README with build #$BUILD_NUMBER"
          sed -i "s/#PLACEHOLDER/$BUILD_NUMBER/g" README.md

      # 3️⃣ Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update build number to #${{ github.run_number }}" || echo "No changes to commit"
          git push
